@startuml



skinparam state {
  BackgroundColor<<Active>> PaleGreen
  BackgroundColor<<Passive>> Gold
  BackgroundColor<<BusOff>> Tomato
  BorderColor Black
}



state "Error Active" as Active <<Active>> : Node can send and receive \nDominant Error Flags which will disturb other nodes
state "Error Passive" as Passive <<Passive>> : Node can send and receive but it sends \nRecessive Error Flags \nin case of error without disturbing the bus
state "Bus Off" as BusOff <<BusOff>> : Transceiver Disabled \n(No TX/RX)

Active -down-> Passive : (TEC > 127)\n||\n(REC > 127)
Passive -up-> Active : (TEC <= 127)\n&&\n(REC <= 127)

Passive -down-> BusOff : TEC > 255

BusOff -left-> Active : 128 x 1\n Recessive Bits\n(Bus Recovery) \n or Reset the transreciver
@enduml